import PDFDocument from "pdfkit";
export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "OmnixAI",
        Title: data.title,
        Creator: "OmnixAI",
      },
    });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));
    //title
    doc
      .fillColor("#111827")
      .fontSize(28)
      .text(data.title, {
        align: "center",
      })

    if (data.subtitle) {
      doc.moveDown(0.5);
    }

    //subtitle
    doc
      .fillColor("#6B7280")
      .fontSize(18)
      .text(data.subtitle, {
        align: "center",
      })

    doc.moveDown(2);
    

    //content

    data?.sections?.forEach((s) => {
      doc.fillColor("#111827").fontSize(18).text(s.heading, {});
      doc.moveDown(1);
      s?.points?.forEach((p) => {
        doc
          .fillColor("#4B5563")
          .fontSize(12)
          .text(`• ${p}`, {
            lineGap: 5,
          })
          
      });
      doc.moveDown();
    });

    //footer divider(line)
    const footerLineY = doc.page.height - 55;
    const footerTextY = doc.page.height - 42;
    doc
      .strokeColor("#E5E7EB")
      .lineWidth(0.75)
      .moveTo(50, footerLineY)
      .lineTo(doc.page.width - 50, footerLineY)
      .stroke();


    //footer
    doc
      .fillColor("#9CA3AF")
      .fontSize(10)
      .text(
        "Generated by OmnixAI • Confidential & Proprietary",
        50,
        footerTextY,
        {
          width: doc.page.width - 100,
          align: "center",
          lineBreak: false,
        },
      );

    doc.end();
  });
};
